### ISSUE TITLE
xcode 16 facing issue while uploading to App Store

### ISSUE THREAD

**Issue by kishangohel** [embrace-io/embrace-flutter-sdk#11]
Error:
Asset validation failed
Invalid Executable. The executable 'Runner.app/Frameworks/Embrace.framework/Embrace' contains bitcode. (ID: f38aaf74-ddd4-41c5-8b4d-45da2b84654f)

Embrace: 2.0.0
xcode: 16.0

**Comment by eliabsisay** [comment]
@kishangohel - thanks for submitting your issue a member of the team will take a look and get back to you shortly.

**Comment by kishangohel** [comment]
@eliabsisay any update?

**Comment by fractalwrench** [comment]
@kishangohel this has been fixed in 3.0.1. Please ping me if you have any further questions.

**Comment by kishangohel** [comment]
@fractalwrench This can be tested further if I can build an application with the latest version
as first [#10] this has to be resolved
