### ISSUE TITLE
Use embrace 6.0 on the platform interfaces

### ISSUE THREAD

**Issue by pastre** [embrace-io/embrace-flutter-sdk#7]
**Is your feature request related to a problem? Please describe.**

Bumping the submodules to 6.x would make this library open-telemetry compliant,
opening up a whole new range of use cases

**Describe the solution you'd like**

`embrace_ios` and `embrace_android` should depend on [embrace-apple-sdk 6.x](https://github.com/embrace-io/embrace-apple-sdk) and [embrace-android-sdk 6.x](https://github.com/embrace-io/embrace-android-sdk)

**Describe alternatives you've considered**

Use a bare open-telemetry library (like [opentelemetry-dart](https://github.com/Workiva/opentelemetry-dart))

**Additional context**

Is this update planned somehow? I'd love to contribute if there are any plans :D

**Comment by eliabsisay** [comment]
@pastre - Thank you for opening this issue. Good news - we're working on that as we speak. We expect the work to bump the dependencies in our Flutter and React Native SDKs to iOS 6.x to be complete in the next 2-3 weeks, and Unity shortly after that. I'll confirm here once they're in prod.

Separately, I'd love to talk to you about your use case. I sent you a connection request on LinkedIn and hopefully, we can find some time to chat.
